# Generated by Django 4.0.4 on 2022-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=16)),
                ('date_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('date_modificado', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['id'],
            },
        ),
    ]
