# Generated by Django 4.0.4 on 2022-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locales',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=16)),
                ('date_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('date_modificado', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Platillos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, unique=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('img_platillo', models.ImageField(blank=True, upload_to='images/platillos')),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
                'ordering': ['id'],
            },
        ),
    ]
