# Generated by Django 4.0.4 on 2022-08-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenerarCodigoBarras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=13)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Codigo de barra',
                'verbose_name_plural': 'Codigos de barras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Img_producto', models.ImageField(blank=True, null=True, upload_to='images/producto')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=499)),
                ('entrega', models.PositiveIntegerField(default=0)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('inventario', models.PositiveIntegerField(default=0)),
                ('salida', models.PositiveBigIntegerField(default=0)),
                ('estado', models.CharField(blank=True, choices=[('pedido', 'Pedido'), ('aceptado', 'Aceptado'), ('cancelado', 'Cancelado'), ('enviado', 'Enviado'), ('Entregado', 'Entregado')], default=False, max_length=10)),
                ('date_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('date_cambiado', models.DateTimeField(auto_now=True, verbose_name='Fehca modificada')),
                ('almacen', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.almacenes')),
                ('categoria', models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='entradas.categoria')),
                ('seleccion_cb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entradas.generarcodigobarras')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['date_creado'],
            },
        ),
    ]
