# Generated by Django 4.0.4 on 2022-08-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurante', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, verbose_name='Orden creada')),
                ('orden_actualizada', models.DateTimeField(auto_now=True, verbose_name='Orden actulizada')),
                ('platillos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurante.platillos')),
                ('usuario', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.users')),
            ],
        ),
        migrations.CreateModel(
            name='cortecaja',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Nd_caja', models.CharField(blank=True, max_length=5)),
                ('MontoInicial', models.CharField(blank=True, max_length=200)),
                ('MontoDCierre', models.CharField(blank=True, max_length=200)),
                ('Fecha_apertura', models.DateField(auto_now=True)),
                ('Hora_apertura', models.TimeField(auto_now=True)),
                ('Fecha_cierre', models.DateField(auto_now=True)),
                ('Hora_cierre', models.TimeField(auto_now=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, verbose_name='Orden creada')),
                ('corte_actualizado', models.DateTimeField(auto_now=True, verbose_name='Orden actulizada')),
                ('platillos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurante.platillos')),
                ('usuario', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.users')),
            ],
        ),
    ]
